import = ["/home/axer/.config/alacritty/theme/havona.toml"]

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[font]
size = 14

[font.normal]
family = "RobotoMono Nerd Font"
